kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: ecommerce
spec:
  selector: 
    app: django_app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
  
