kind: Deployment
apiVersion: apps/v1
metadata:
  name: django-app
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django_app
  template:
    metadata:
      labels:
        app: django_app
    spec:
      containers:
      - name: django-dep
        image: tarasankar393/django-ecommerce-app:v1.0.1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secret
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
