kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-media-pvc
  namespace: ecommerce
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi