kind: PersistentVolume
apiVersion: v1
metadata:
  name: django-media-pv
  namespace: ecommerce
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/django-media