kind: Secret
apiVersion: v1
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: "em$adv+@p6-^c8!&9$whr@dwt77(k00w*l%_(3wfg6xlk2=euz"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DJANGO_SUPERUSER_PASSWORD: "eW91cnBhc3N3b3Jk"