kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: e-commerce
spec:
  selector: 
    app: mysql_app
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
