kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-app
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql_app
  template:
    metadata:
      labels:
        app: mysql_app
    spec:
      containers:
      - name: mysql-dep
        image: mysql:8.4
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "mydatabase"
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc