kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/mysql