# Generated by Django 5.1.6 on 2025-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='signup',
            name='pin',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mob',
            field=models.IntegerField(default=None),
        ),
    ]
