# Generated by Django 5.1.6 on 2025-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_signup_email_alter_signup_mob_alter_signup_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mob',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='pin',
            field=models.IntegerField(max_length=20),
        ),
    ]
