# Generated by Django 5.1.6 on 2025-03-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_signup_email_alter_signup_mob_alter_signup_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pin',
            new_name='pinc',
        ),
    ]
