# Generated by Django 5.1.6 on 2025-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_pin_signup_pinc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='pinc',
            field=models.IntegerField(),
        ),
    ]
