# Generated by Django 5.1.6 on 2025-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_signup_pinc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='pinc',
        ),
        migrations.AddField(
            model_name='signup',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
