# Generated by Django 6.0.4 on 2026-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_signup_pinc_signup_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mob',
            field=models.CharField(max_length=15),
        ),
    ]
