# Generated by Django 6.0.4 on 2026-07-16 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beautyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('b_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='beautySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='decorContent',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('d_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='decorSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='electronicsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('e_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='electronicsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='homeContSlider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url1', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='homeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='kidContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('k_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='kidSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='menContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('men_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='mobileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('m_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mobileSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='womenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('w_title', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('dis_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='womenSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='homeContSlider2',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('slide_url2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagories')),
            ],
        ),
    ]
