# Generated by Django 5.1.6 on 2025-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menContent',
            fields=[
                ('main_url', models.URLField(max_length=500)),
                ('image_url', models.URLField(max_length=500, primary_key=True, serialize=False)),
                ('men_title', models.CharField(max_length=60)),
                ('total', models.FloatField(max_length=10)),
                ('discount', models.FloatField(max_length=10)),
                ('dis_price', models.FloatField(max_length=10)),
            ],
        ),
    ]
