# Generated by Django 5.1.6 on 2025-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mencontent',
            name='dis_price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='discount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='total',
            field=models.IntegerField(max_length=10),
        ),
    ]
