# Generated by Django 5.1.6 on 2025-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_mencontent_dis_price_alter_mencontent_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wSlider',
            fields=[
                ('slide_url', models.URLField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
