# Generated by Django 5.1.6 on 2025-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_wslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='wContent',
            fields=[
                ('main_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(max_length=500, primary_key=True, serialize=False)),
                ('men_title', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
            ],
        ),
    ]
