# Generated by Django 5.1.6 on 2025-02-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcontent',
            name='main_url',
            field=models.URLField(max_length=1500),
        ),
    ]
