# Generated by Django 5.1.6 on 2025-02-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_wcontent_main_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wcontent',
            old_name='men_title',
            new_name='w_title',
        ),
    ]
