# Generated by Django 5.1.6 on 2025-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_men_title_wcontent_w_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='bContent',
            fields=[
                ('main_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=1000, primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bSlider',
            fields=[
                ('slide_url', models.URLField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='dContent',
            fields=[
                ('main_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=1000, primary_key=True, serialize=False)),
                ('d_title', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dSlider',
            fields=[
                ('slide_url', models.URLField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='eContent',
            fields=[
                ('main_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=1000, primary_key=True, serialize=False)),
                ('e_title', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='eSlider',
            fields=[
                ('slide_url', models.URLField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='kContent',
            fields=[
                ('main_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=1000, primary_key=True, serialize=False)),
                ('k_title', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kSlider',
            fields=[
                ('slide_url', models.URLField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='mContent',
            fields=[
                ('main_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=1000, primary_key=True, serialize=False)),
                ('m_title', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mSlider',
            fields=[
                ('slide_url', models.URLField(max_length=2000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='image_url',
            field=models.URLField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='main_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='menslider',
            name='slide_url',
            field=models.URLField(max_length=2000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wcontent',
            name='image_url',
            field=models.URLField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wcontent',
            name='main_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='wslider',
            name='slide_url',
            field=models.URLField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
