# Generated by Django 5.1.6 on 2025-02-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bcontent_bslider_dcontent_dslider_econtent_eslider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bContent',
            new_name='beautyContent',
        ),
        migrations.RenameModel(
            old_name='mSlider',
            new_name='beautySlider',
        ),
        migrations.RenameModel(
            old_name='dContent',
            new_name='decorContent',
        ),
        migrations.RenameModel(
            old_name='wSlider',
            new_name='decorSlider',
        ),
        migrations.RenameModel(
            old_name='eContent',
            new_name='electronicsContent',
        ),
        migrations.RenameModel(
            old_name='bSlider',
            new_name='electronicsSlider',
        ),
        migrations.RenameModel(
            old_name='mContent',
            new_name='kidContent',
        ),
        migrations.RenameModel(
            old_name='eSlider',
            new_name='kidSlider',
        ),
        migrations.RenameModel(
            old_name='kContent',
            new_name='mobileContent',
        ),
        migrations.RenameModel(
            old_name='dSlider',
            new_name='mobileSlider',
        ),
        migrations.RenameModel(
            old_name='wContent',
            new_name='womenContent',
        ),
        migrations.RenameModel(
            old_name='kSlider',
            new_name='womenSlider',
        ),
        migrations.RenameField(
            model_name='kidcontent',
            old_name='m_title',
            new_name='k_title',
        ),
        migrations.RenameField(
            model_name='mobilecontent',
            old_name='k_title',
            new_name='m_title',
        ),
    ]
