# Generated by Django 5.1.6 on 2025-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_bcontent_beautycontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautycontent',
            name='b_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='decorcontent',
            name='d_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='electronicscontent',
            name='e_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='k_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='men_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobilecontent',
            name='m_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='womencontent',
            name='w_title',
            field=models.CharField(max_length=200),
        ),
    ]
