# Generated by Django 5.1.6 on 2025-02-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_beautycontent_b_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautycontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='beautyslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='decorcontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='decorslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='electronicscontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='electronicsslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='kidcontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='kidslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mencontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='menslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mobilecontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mobileslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='womencontent',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='womenslider',
            name='id',
            field=models.IntegerField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beautycontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='beautyslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='decorcontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='decorslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='electronicscontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='electronicsslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='kidslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='menslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mobilecontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='mobileslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='womencontent',
            name='image_url',
            field=models.URLField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='womenslider',
            name='slide_url',
            field=models.URLField(max_length=2000),
        ),
    ]
