# Generated by Django 5.1.6 on 2025-03-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_beautycontent_id_alter_beautycontent_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeContSlider1',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('slide_url1', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='homeContSlider2',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('slide_url2', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='homeSlider',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('slide_url', models.URLField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='beautycontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beautycontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='decorcontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='decorcontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicscontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicscontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kidcontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mencontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilecontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilecontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='womencontent',
            name='dis_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='womencontent',
            name='total',
            field=models.CharField(max_length=20),
        ),
    ]
