# Generated by Django 5.1.6 on 2025-03-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_catagories_homecontslider2_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagories',
            name='id',
        ),
        migrations.AlterField(
            model_name='catagories',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homecontslider2',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagories'),
        ),
    ]
