kind: Application
apiVesion: argoproj.io/v1alpha1
metadata:
  name: webmart
  namespace: argocd
spec:
  project: default
  source:
    repoUrl: "https://github.com/Tarasankar-create/webmart-web.git"
    tarhetRevision: prod
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true